### ISSUE TITLE
Trigger transition by event

### ISSUE THREAD

**Issue by wavebit** [Recursoft/LogicDriver-Example#3]
Hello,
From the wiki [https://github.com/Recursoft/LogicDriver-Example/wiki/Transitions](url), the transition must be a pure function return true or false, so we have to create a temporary state variable (outside the transition scope) if the transition is triggered by an event. 
If there are OnEnterEvent, OnExitEvent and a trigger callback functions in transition scope, then we have a chance to watch a specific event to trigger the transition and unwatch event.

**Comment by pshardy** [comment]
Hey @wavebit, let me make sure I understand. If you want to trigger a state change by an event, you need to create a variable (in the context or elsewhere) that your event can change so the transition can read the variable change and trigger.

And you would prefer to avoid that by having an event trigger the transition directly?

Sorry for the delay in responding!

**Comment by pshardy** [comment]
Not sure if you're still interested in this but I thought expanding the transition graph is a good idea. I've implemented something that should do what you want.

![image](https://user-images.githubusercontent.com/3743909/61166726-7347d980-a4e7-11e9-8754-3b234732b24e.png)

Some new optional nodes will be in the next update:
- On Transition Initialized (When the state leading to the transition is entered)
- On Transition Shutdown (When the state leading to the transition is exited)
- Before Evaluate (Before each evaluation)
- After Evaluate (After each evaluation)

- Can Evaluate Getter/Setter which can be used in the transition context. If false the transition is never evaluated.

**Comment by wavebit** [comment]
Glad to see you expanded this plugin. Sorry, I missed the github messages before.

**Comment by pshardy** [comment]
Implemented in 1.4
