### ISSUE TITLE
Nested static machine error

### ISSUE THREAD

**Issue by michaelchen2010** [Recursoft/LogicDriver-Example#4]
A bug found: When leaves from nested static machine, current state's "OnStateBegin" will be called again. I've fixed it like the following:
bool FSMStateMachine::EndState(float DeltaSeconds)
{
......
	if (CurrentState)
	{
		CurrentState->EndState(DeltaSeconds);

		if (!CanReuseCurrentState())
		{
			SetCurrentState(nullptr);
		}
	}

	//ProcessStates(DeltaSeconds);  // comment out this line

	return true;
}

**Comment by pshardy** [comment]
Thanks for reporting this and sharing your solution. I'll take a look and do some tests and try to include this fix or something similar in the next update.

**Comment by pshardy** [comment]
Thanks again for reporting this. It's fixed in 1.6 which is pending review. You're right that ProcessStates wasn't necessary to call there.
